name: CI   # Name of the workflow (appears in the Actions tab)

on:
  push:            # Run CI when code is pushed to the repo
    branches: [ main ]   # Only for pushes to the main branch
  pull_request:    # Run CI on every pull request targeting main
    branches: [ main ]

jobs:
  build-and-test:     # The job name
    runs-on: ubuntu-latest   # Spin up a fresh Ubuntu VM in GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This clones your repository into the VM so the workflow can access your code

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
        # This downloads and installs pixi
        # Then adds pixi to the PATH so future steps can use it

      - name: Install dependencies
        run: pixi install
        # This installs everything declared in your pixi.toml
        # (Python, R, testthat, pytest, etc.)

      - name: Run tests
        run: pixi run test
        # This runs your "meta task" which executes:
        # 1. Python tests (pytest)
        # 2. R tests (testthat)
        # 3. Shell tests (bash)
