name: CI   # Name of the workflow (appears in the Actions tab)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true   # enable dependency caching
          post-cleanup: false
          locked: false  # Don't use --locked flag

      - name: Run tests
        run: pixi run test
        # This will run all your meta-tasks (pytest, testthat, bash tests, etc.)

  commitizen-check:
    runs-on: ubuntu-latest
    name: Commitizen check for all commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history needed for commit check

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true

      - name: Check latest commit message with Commitizen
        run: |
          MSG_FILE=$(mktemp)
          git log -1 --pretty=%B > $MSG_FILE
          pixi run cz check --commit-msg-file $MSG_FILE
