name: Lint & Style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true  # speeds up repeated runs

      - name: Run Ruff (lint)
        run: pixi run ruff check .

      - name: Run Black (check format)
        run: pixi run black --check .

      - name: Run isort (check imports)
        run: pixi run isort --check-only .
